name: Build Android APK
env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  ENCODED_STRING: ${{ secrets.KEYSTORE_BASE64 }}
  
  run: ./gradlew assembleRelease

on:
  workflow_dispatch: # Этот параметр открывает кнопку ручного запуска в интерфейсе

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Decode Keystore
        run: 
          echo "$ENCODED_STRING" | base64 --decode > app/my-upload-key.jks
        
      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build Release APK
        run: ./gradlew assembleRelease # Команда для сборки релизного APK
        
